### ISSUE TITLE
Transcript of Fortran programs

### ISSUE THREAD

**Issue by cibinjoseph** [alwinw/KatzPlotkinPy#15]
Hey, I had a transcript of some of the Fortran programs in the book [here.](https://github.com/cibinjoseph/KatzPlotkin) You might find them helpful to verify your Python program versions against. Do you accept pull requests? I might be able to contribute.

**Comment by alwinw** [comment]
Hey @cibinjoseph that's great! I've transcribed most of them as well, here: https://github.com/alwinw/KatzPlotkinPy/tree/master/tests/f77

I think I'm only missing programs 15 and 16 and would be happy to accept a pull request for them, thanks!

**Comment by cibinjoseph** [comment]
Program 15 and 16 have been added in pull request #16
